name: Auto Assign to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign NEW issues and NEW pull requests to "mottai-matching-app" project
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project: 'https://github.com/npo-mottai/mottai-matching-app/projects/1'

      - name: Assign all issues and pull requests on this repository to the project
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/npo-mottai/mottai-matching-app/projects/1'
          column_name: 'To do'
